// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { auth, defineMcp } from "npm:@lovable.dev/mcp-js@0.24.0";

// src/lib/mcp/tools/get-me.ts
import { createClient } from "npm:@supabase/supabase-js@^2.93.3";
import { defineTool } from "npm:@lovable.dev/mcp-js@0.24.0";
function sbForUser(ctx) {
  return createClient(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var get_me_default = defineTool({
  name: "get_me",
  title: "Get my profile",
  description: "Return the currently signed-in idealniepasuje user: user id, email, user type (candidate or employer), and either the candidate additional info or the employer company profile.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async (_input, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const sb = sbForUser(ctx);
    const userId = ctx.getUserId();
    const { data: profile } = await sb.from("profiles").select("user_type, full_name").eq("user_id", userId).maybeSingle();
    let extra = null;
    if (profile?.user_type === "candidate") {
      const { data } = await sb.from("candidate_test_results").select("industry, position_level, experience, city, work_mode, linkedin_url, all_tests_completed, profile_ready").eq("user_id", userId).maybeSingle();
      extra = data;
    } else if (profile?.user_type === "employer") {
      const { data } = await sb.from("employer_profiles").select("company_name, city, culture_completed").eq("user_id", userId).maybeSingle();
      extra = data;
    }
    const payload = {
      user_id: userId,
      email: ctx.getUserEmail?.() ?? null,
      user_type: profile?.user_type ?? null,
      full_name: profile?.full_name ?? null,
      details: extra
    };
    return {
      content: [{ type: "text", text: JSON.stringify(payload, null, 2) }],
      structuredContent: payload
    };
  }
});

// src/lib/mcp/tools/list-my-matches.ts
import { createClient as createClient2 } from "npm:@supabase/supabase-js@^2.93.3";
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.24.0";
import { z } from "npm:zod@^3.25.76";
function sbForUser2(ctx) {
  return createClient2(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var list_my_matches_default = defineTool2({
  name: "list_my_matches",
  title: "List my matches",
  description: "List match results visible to the signed-in user. For candidates: matches with employer job offers. For employers: matches for their own job offers. Returns overall match percentage, status and linked offer/candidate ids.",
  inputSchema: {
    limit: z.number().int().min(1).max(50).describe("Max number of matches to return.").optional()
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ limit }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const sb = sbForUser2(ctx);
    const { data, error } = await sb.from("match_results").select("id, candidate_user_id, employer_user_id, job_offer_id, overall_percent, status, created_at").order("overall_percent", { ascending: false }).limit(limit ?? 20);
    if (error) {
      return { content: [{ type: "text", text: error.message }], isError: true };
    }
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? [], null, 2) }],
      structuredContent: { matches: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/list-my-offers.ts
import { createClient as createClient3 } from "npm:@supabase/supabase-js@^2.93.3";
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.24.0";
function sbForUser3(ctx) {
  return createClient3(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var list_my_offers_default = defineTool3({
  name: "list_my_offers",
  title: "List my job offers",
  description: "For employers: list the job offers owned by the signed-in employer. For candidates this returns an empty list.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async (_input, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const sb = sbForUser3(ctx);
    const { data, error } = await sb.from("job_offers").select("id, title, industry, position_level, is_active, created_at").order("created_at", { ascending: false }).limit(50);
    if (error) {
      return { content: [{ type: "text", text: error.message }], isError: true };
    }
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? [], null, 2) }],
      structuredContent: { offers: data ?? [] }
    };
  }
});

// src/lib/mcp/index.ts
var projectRef = "yqqubonlxloyhmicdfhi";
var mcp_default = defineMcp({
  name: "idealniepasuje-mcp",
  title: "idealnie pasuje",
  version: "0.1.0",
  instructions: "Tools for the idealnie pasuje recruitment platform. Use `get_me` to identify the signed-in user (candidate or employer). Use `list_my_matches` to see match results, and `list_my_offers` (employers only) to list posted job offers. All data is scoped to the signed-in user by RLS.",
  auth: auth.oauth.issuer({
    issuer: `https://${projectRef}.supabase.co/auth/v1`,
    acceptedAudiences: "authenticated"
  }),
  tools: [get_me_default, list_my_matches_default, list_my_offers_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.24.0/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
